export const questions = [
  {
    id: 1,
    question: "Was versteht man unter \"Hatespeech\"?",
    answers: [
      { text: "Beleidigungen gegen den Computer", correct: false },
      { text: "Hassrede, die sich gegen Personen oder Gruppen richtet", correct: true },
      { text: "Ironische Kommentare in einem Spiel", correct: false },
      { text: "Scherzhafte Kritik am Spiel", correct: false },
    ],
    explanation: "Hatespeech bezeichnet diskriminierende oder herabwürdigende Äußerungen gegenüber Personen oder Gruppen.",
  },
  {
    id: 2,
    question: "Welche dieser Aussagen gilt als Hatespeech?",
    answers: [
      { text: "„Du bist echt gut in diesem Spiel!“", correct: false },
      { text: "„Frauen können gar nicht zocken, geh in die Küche!“", correct: true },
      { text: "„Ich finde das Spiel langweilig.“", correct: false },
      { text: "„Du spielst wie ein Profi!“", correct: false },
    ],
    explanation: "Die Aussage richtet sich abwertend gegen eine bestimmte Gruppe, was als Hatespeech gilt.",
  },
  {
    id: 3,
    question: "Was ist ein typisches Ziel von Hatespeech im Gaming?",
    answers: [
      { text: "Spieler zu motivieren", correct: false },
      { text: "Diskriminierung und Herabwürdigung anderer", correct: true },
      { text: "Die Spielmechanik zu erklären", correct: false },
      { text: "Feedback an die Entwickler zu geben", correct: false },
    ],
    explanation: "Das Ziel von Hatespeech ist es, andere zu diskriminieren und herabzuwürdigen.",
  },
  {
    id: 4,
    question: "Welche Gruppen sind im Gaming besonders häufig von Hatespeech betroffen?",
    answers: [
      { text: "Profispieler", correct: false },
      { text: "Frauen, LGBTQ+ Personen und Minderheiten", correct: true },
      { text: "Spieler mit hoher Punktzahl", correct: false },
      { text: "Alle Spieler gleichermaßen", correct: false },
    ],
    explanation: "Besonders Frauen, LGBTQ+ Personen und Minderheiten sind häufig von Hatespeech betroffen.",
  },
  {
    id: 5,
    question: "Wie könnte man auf Hatespeech in einer Gaming-Community reagieren?",
    answers: [
      { text: "Sie ignorieren", correct: false },
      { text: "Den Täter beleidigen", correct: false },
      { text: "Die Situation melden und moderieren lassen", correct: true },
      { text: "Sich vollständig aus der Community zurückziehen", correct: false },
    ],
    explanation: "Die beste Reaktion auf Hatespeech ist es, die Situation zu melden und moderieren zu lassen.",
  },
  {
    id: 6,
    question: "Wie bezeichnet man Personen, die absichtlich Hatespeech betreiben?",
    answers: [
      { text: "Moderatoren", correct: false },
      { text: "Trolle", correct: true },
      { text: "Entwickler", correct: false },
      { text: "Speedrunner", correct: false },
    ],
    explanation: "Personen, die absichtlich Hatespeech betreiben, werden als Trolle bezeichnet.",
  },
  {
    id: 7,
    question: "Was ist ein häufiger Grund für Hatespeech im Gaming?",
    answers: [
      { text: "Frustration über das Spiel", correct: false },
      { text: "Langeweile", correct: false },
      { text: "Machtgefühl und Anonymität im Internet", correct: true },
      { text: "Schlechte Grafik", correct: false },
    ],
    explanation: "Ein häufiger Grund für Hatespeech ist das Machtgefühl und die Anonymität im Internet.",
  },
  {
    id: 8,
    question: "Welche Plattform hat laut Studien am meisten mit Hatespeech zu kämpfen?",
    answers: [
      { text: "PC-Spiele", correct: false },
      { text: "Konsolen-Spiele", correct: false },
      { text: "Mobile Games", correct: false },
      { text: "Online-Multiplayer-Plattformen", correct: true },
    ],
    explanation: "Online-Multiplayer-Plattformen haben laut Studien am meisten mit Hatespeech zu kämpfen.",
  },
  {
    id: 9,
    question: "Wie kann man als Spieler aktiv gegen Hatespeech vorgehen?",
    answers: [
      { text: "Täter ermutigen, weiterzumachen", correct: false },
      { text: "Stillschweigen bewahren", correct: false },
      { text: "Betroffene unterstützen und Fälle melden", correct: true },
      { text: "Das Spiel löschen", correct: false },
    ],
    explanation: "Als Spieler kann man aktiv gegen Hatespeech vorgehen, indem man Betroffene unterstützt und Fälle meldet.",
  },
  {
    id: 10,
    question: "Welche dieser Aussagen ist ein Mythos über Hatespeech?",
    answers: [
      { text: "„Es betrifft nur große Plattformen.“", correct: true },
      { text: "„Jeder kann von Hatespeech betroffen sein.“", correct: false },
      { text: "„Hatespeech kann psychologische Schäden verursachen.“", correct: false },
      { text: "„Es gibt nichts, was man gegen Hatespeech tun kann.“", correct: false },
    ],
    explanation: "Der Mythos, dass Hatespeech nur große Plattformen betrifft, ist falsch.",
  },
  {
    id: 11,
    question: "Was ist eine mögliche Folge von Hatespeech im Gaming?",
    answers: [
      { text: "Spieler steigern ihre Leistung", correct: false },
      { text: "Betroffene fühlen sich ausgeschlossen und unsicher", correct: true },
      { text: "Spiele werden realistischer", correct: false },
      { text: "Gemeinschaften werden stärker", correct: false },
    ],
    explanation: "Eine mögliche Folge von Hatespeech ist, dass sich Betroffene ausgeschlossen und unsicher fühlen.",
  },
  {
    id: 12,
    question: "Wie oft geben Frauen an, Hatespeech in Gaming-Communities zu erleben?",
    answers: [
      { text: "Selten", correct: false },
      { text: "Nie", correct: false },
      { text: "Häufig", correct: true },
      { text: "Immer", correct: false },
    ],
    explanation: "Frauen geben häufig an, Hatespeech in Gaming-Communities zu erleben.",
  },
  {
    id: 13,
    question: "Was bedeutet der Begriff \"toxische Community\"?",
    answers: [
      { text: "Eine Community, die viele hilfreiche Tipps gibt", correct: false },
      { text: "Eine Community mit aggressivem, beleidigendem Verhalten", correct: true },
      { text: "Eine Community für Anfänger", correct: false },
      { text: "Eine geschlossene Gruppe von Freunden", correct: false },
    ],
    explanation: "Eine toxische Community ist eine Community mit aggressivem, beleidigendem Verhalten.",
  },
  {
    id: 14,
    question: "Welche dieser Maßnahmen kann Hatespeech in Gaming-Chats verringern?",
    answers: [
      { text: "Einführung von Moderations-Tools", correct: true },
      { text: "Keine Strafen für toxisches Verhalten", correct: false },
      { text: "Spieler ohne Einschränkungen kommunizieren lassen", correct: false },
      { text: "Anonymität garantieren", correct: false },
    ],
    explanation: "Die Einführung von Moderations-Tools kann Hatespeech in Gaming-Chats verringern.",
  },
  {
    id: 15,
    question: "Welche Organisation setzt sich international gegen Hatespeech ein?",
    answers: [
      { text: "FIFA", correct: false },
      { text: "United Nations (UN)", correct: true },
      { text: "World of Warcraft", correct: false },
      { text: "OpenAI", correct: false },
    ],
    explanation: "Die United Nations (UN) setzt sich international gegen Hatespeech ein.",
  },
  {
    id: 16,
    question: "Warum ist Hatespeech nicht nur ein Problem für einzelne Spieler?",
    answers: [
      { text: "Es beeinflusst die gesamte Gaming-Community negativ", correct: true },
      { text: "Es macht Spiele teurer", correct: false },
      { text: "Es betrifft nur bestimmte Genres", correct: false },
      { text: "Es reduziert die Serverkapazität", correct: false },
    ],
    explanation: "Hatespeech beeinflusst die gesamte Gaming-Community negativ.",
  },
  {
    id: 17,
    question: "Welche Gesetze greifen in Deutschland gegen Hatespeech?",
    answers: [
      { text: "Grundgesetz und Netzwerkdurchsetzungsgesetz (NetzDG)", correct: true },
      { text: "Straßenverkehrsordnung", correct: false },
      { text: "Urheberrechtsgesetz", correct: false },
      { text: "Baurecht", correct: false },
    ],
    explanation: "In Deutschland greifen das Grundgesetz und das Netzwerkdurchsetzungsgesetz (NetzDG) gegen Hatespeech.",
  },
  {
    id: 18,
    question: "Was ist ein Beispiel für indirekte Hatespeech?",
    answers: [
      { text: "Klare Beleidigungen", correct: false },
      { text: "Sarkastische, abwertende Bemerkungen", correct: true },
      { text: "Ein Lob für einen Spieler", correct: false },
      { text: "Technische Fehler melden", correct: false },
    ],
    explanation: "Indirekte Hatespeech umfasst sarkastische, abwertende Bemerkungen.",
  },
  {
    id: 19,
    question: "Warum ist Anonymität im Gaming ein Faktor bei Hatespeech?",
    answers: [
      { text: "Sie schützt vor Cybermobbing", correct: false },
      { text: "Sie macht Täter mutiger, weil es weniger Konsequenzen gibt", correct: true },
      { text: "Sie reduziert toxisches Verhalten", correct: false },
      { text: "Sie sorgt für bessere Leistung im Spiel", correct: false },
    ],
    explanation: "Anonymität im Gaming macht Täter mutiger, weil es weniger Konsequenzen gibt.",
  },
  {
    id: 20,
    question: "Was ist eine wirksame Methode, toxisches Verhalten zu vermeiden?",
    answers: [
      { text: "Präventive Bildung über respektvollen Umgang", correct: true },
      { text: "Alle Chats deaktivieren", correct: false },
      { text: "Nur mit Freunden spielen", correct: false },
      { text: "Schlechte Spieler blockieren", correct: false },
    ],
    explanation: "Präventive Bildung über respektvollen Umgang ist eine wirksame Methode, toxisches Verhalten zu vermeiden.",
  },
];

export const prizeSums = [
  { id: 1, amount: "100 €" },
  { id: 2, amount: "200 €" },
  { id: 3, amount: "300 €" },
  { id: 4, amount: "400 €" },
  { id: 5, amount: "500 €" },
  { id: 6, amount: "600 €" },
  { id: 7, amount: "700 €" },
  { id: 8, amount: "800 €" },
  { id: 9, amount: "900 €" },
  { id: 10, amount: "1.000 €" },
  { id: 11, amount: "2.000 €" },
  { id: 12, amount: "4.000 €" },
  { id: 13, amount: "8.000 €" },
  { id: 14, amount: "16.000 €" },
  { id: 15, amount: "32.000 €" },
  { id: 16, amount: "64.000 €" },
  { id: 17, amount: "125.000 €" },
  { id: 18, amount: "500.000 €" },
  { id: 19, amount: "1.000.000 €" },
];
